/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3ba1475c1ac97c6b1d215902a087de48)
interface __BaseEnv_Env {
  MEDIA: R2Bucket;
  DB: D1Database;
  EMAIL: SendEmail;
  STREAM: StreamBinding;
  WEB_ORIGIN: "https://preview.mytuums.com";
  EMAIL_FROM: "noreply@mytuums.com";
  STREAM_NAMESPACE: "mytuums-preview";
  CLOUDFLARE_ACCOUNT_ID: "734f3b84571b1967e6940140a0b7d75f";
  STREAM_API_TOKEN: string;
  IGDB_CLIENT_ID: string;
  IGDB_CLIENT_SECRET: string;
  APPEAL_TOKEN_SECRET: string;
  VIDEO_WORKFLOW: Workflow<Parameters<import("./src/index").VideoWorkflow["run"]>[0]["payload"]>;
  MAINTENANCE_WORKFLOW: Workflow<
    Parameters<import("./src/index").MaintenanceWorkflow["run"]>[0]["payload"]
  >;
  GAME_SYNC_WORKFLOW: Workflow<
    Parameters<import("./src/index").GameSyncWorkflow["run"]>[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "WEB_ORIGIN"
      | "EMAIL_FROM"
      | "STREAM_NAMESPACE"
      | "CLOUDFLARE_ACCOUNT_ID"
      | "STREAM_API_TOKEN"
      | "IGDB_CLIENT_ID"
      | "IGDB_CLIENT_SECRET"
      | "APPEAL_TOKEN_SECRET"
    >
  > {}
}
