import { Link } from "@tanstack/react-router";

export function PrivacyPolicyEn() {
  return (
    <>
      <em>
        This is a courtesy translation. The French version is the legally authoritative one and
        governs in case of any discrepancy — switch language via the footer selector to read it.
      </em>

      <p>
        MyTuums (the "Service") is a non-professional, non-profit social app run by a single
        individual (the "operator", "we"). This policy explains what personal data we process
        when you use the Service, why, for how long, and what rights you have.
      </p>
      <p>
        Read this alongside the <Link to="/mentions-legales">mentions légales</Link> (French
        legal notice), which identifies the operator and the host.
      </p>

      <h2>1. Data controller</h2>
      <p>
        The data controller, within the meaning of Article 4(7) GDPR, is the site operator
        identified in the <Link to="/mentions-legales">mentions légales</Link>, reachable at
        contact@mytuums.com for any question about your data.
      </p>
      <p>
        Given the size and nature of the processing (a non-professional, non-profit app run by
        one person), no Data Protection Officer has been appointed — this isn't required under
        GDPR at this scale. The contact address above is the single point of contact.
      </p>

      <h2>2. Data we collect</h2>
      <table>
        <thead>
          <tr>
            <th>Data</th>
            <th>Source</th>
            <th>Why</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Email address</td>
            <td>Provided at sign-up</td>
            <td>Account identifier, account-related communication</td>
          </tr>
          <tr>
            <td>Username and display username</td>
            <td>Provided at sign-up</td>
            <td>Public identification on the Service</td>
          </tr>
          <tr>
            <td>Display name</td>
            <td>Provided at sign-up</td>
            <td>Shown on your profile and posts</td>
          </tr>
          <tr>
            <td>Date of birth</td>
            <td>Provided at sign-up</td>
            <td>Enforcing the 15+ age requirement (see Section 10)</td>
          </tr>
          <tr>
            <td>Password</td>
            <td>Provided at sign-up</td>
            <td>
              Authentication — <strong>never stored in plain text</strong>, only as a
              cryptographic hash (BetterAuth / scrypt)
            </td>
          </tr>
          <tr>
            <td>Profile photo, if you add one</td>
            <td>Provided by you</td>
            <td>Shown on your profile</td>
          </tr>
          <tr>
            <td>Content you post (posts, replies)</td>
            <td>Provided by you</td>
            <td>Core functioning of the Service: these are public posts</td>
          </tr>
          <tr>
            <td>Likes and follows</td>
            <td>Generated by your usage</td>
            <td>Core functioning of the Service (feeds, counts)</td>
          </tr>
          <tr>
            <td>IP address and user agent at sign-in</td>
            <td>Collected automatically</td>
            <td>Session security, abuse prevention</td>
          </tr>
          <tr>
            <td>Session token (cookie)</td>
            <td>Generated at sign-in</td>
            <td>Keeps you signed in</td>
          </tr>
          <tr>
            <td>Rate-limit counters</td>
            <td>Generated automatically</td>
            <td>Preventing spam/abuse (e.g. mass liking or following)</td>
          </tr>
        </tbody>
      </table>
      <p>
        We do <strong>not</strong> collect payment data (the Service is free), precise location
        data, and we do not use any third-party analytics or advertising tools today.
      </p>
      <p>
        <strong>Public by default:</strong> as on most social apps, your posts, replies, likes,
        and follows are visible to other users — the Service requires an account to be viewed.
        Don't post anything you don't want to be public.
      </p>

      <h2>3. Purposes and legal bases (GDPR Article 6)</h2>
      <ul>
        <li>
          <strong>
            Creating and managing your account, and displaying your posts, likes, and follows
          </strong>{" "}
          — performance of the contract formed when you create and use an account (Art. 6(1)(b)
          GDPR): these are exactly the features you're signing up for.
        </li>
        <li>
          <strong>IP address, user agent, session tokens, rate-limit counters</strong> —
          legitimate interest (Art. 6(1)(f) GDPR) in securing accounts, detecting abuse, and
          preventing spam, with limited privacy impact relative to that purpose.
        </li>
        <li>
          <strong>Responding to lawful requests, complying with legal obligations</strong> —
          legal obligation (Art. 6(1)(c) GDPR).
        </li>
      </ul>
      <p>
        We do not carry out automated profiling with legal effects on you, nor any fully
        automated decision-making about you.
      </p>

      <h2>4. Who we share data with</h2>
      <p>
        Your data is <strong>never sold</strong>. It is shared only with:
      </p>
      <ul>
        <li>
          <strong>Railway Corporation</strong> (see{" "}
          <Link to="/mentions-legales">mentions légales</Link>), our sole technical processor,
          which hosts the database and application server. Railway acts as a processor under
          Article 28 GDPR, under its own Data Processing Addendum (
          <a href="https://railway.com/legal/dpa">railway.com/legal/dpa</a>).
        </li>
        <li>Competent authorities, only when legally required.</li>
      </ul>
      <p>
        We use no third-party analytics, advertising, or email-sending services today. If that
        changes, this policy will be updated before rollout, and your consent will be requested
        wherever the law requires it (in particular for any non-essential cookies).
      </p>

      <h2>5. International transfers</h2>
      <p>
        The Service's compute and database run in Railway's EU region. Railway Corporation is
        nonetheless a US company: some residual access from the US (technical support,
        underlying infrastructure) cannot be entirely ruled out.
      </p>
      <p>
        That potential transfer is covered by the safeguards in Railway's Data Processing
        Addendum (the European Commission's Standard Contractual Clauses and/or the EU-U.S. Data
        Privacy Framework), in line with Chapter V of the GDPR.
      </p>

      <h2>6. Cookies</h2>
      <p>
        The Service uses a single session cookie (issued by BetterAuth), strictly necessary to
        keep you signed in. Under CNIL cookie guidance, this cookie is exempt from consent
        requirements because it's essential to the service you've explicitly requested.
      </p>
      <p>No analytics, advertising, or third-party tracking cookies are used today.</p>

      <h2>7. Retention</h2>
      <ul>
        <li>
          <strong>Account data</strong> (email, username, password, profile photo): kept for as
          long as your account exists.
        </li>
        <li>
          <strong>Content</strong> (posts, replies, likes, follows): kept for as long as your
          account exists; deleted along with your account (cascading deletion at the database
          level).
        </li>
        <li>
          <strong>Account deletion</strong>: on request at contact@mytuums.com, your data is
          erased within 30 days, except for residual copies in technical backups, which are
          purged within a maximum of 90 days.
        </li>
        <li>
          <strong>Session data</strong> (token, IP, user agent): sessions expire automatically
          after 7 days of inactivity, or immediately on sign-out.
        </li>
        <li>
          <strong>Rate-limit counters</strong>: kept only as long as needed to enforce the
          relevant limit (minutes to hours, depending on the action).
        </li>
      </ul>

      <h2>8. Security</h2>
      <p>
        Passwords are hashed, never stored in plain text. Communication with the Service is
        encrypted (HTTPS/TLS). Database access is restricted to the application infrastructure.
        No system is infallible, and we can't guarantee absolute security, but we commit to
        notifying you without undue delay of any breach involving your data that's likely to
        result in a high risk to your rights, as required by Article 34 GDPR.
      </p>

      <h2>9. Your rights</h2>
      <p>Under GDPR and French data protection law, you have the right to:</p>
      <ul>
        <li>
          <strong>Access</strong> — get a copy of the data we hold about you.
        </li>
        <li>
          <strong>Rectification</strong> — correct inaccurate data.
        </li>
        <li>
          <strong>Erasure</strong> — request deletion of your account and data.
        </li>
        <li>
          <strong>Restriction of processing</strong>, in the cases provided by law.
        </li>
        <li>
          <strong>Portability</strong> — receive your data in a structured, commonly-used format.
        </li>
        <li>
          <strong>Object</strong>, to processing based on legitimate interest (Section 3).
        </li>
      </ul>
      <p>
        To exercise any of these rights, email contact@mytuums.com. We'll respond within one
        month, as required by Article 12 GDPR.
      </p>
      <p>
        You also have the right to lodge a complaint with the competent supervisory authority. In
        France, that's the <strong>CNIL</strong>: 3 Place de Fontenoy, TSA 80715, 75334 Paris
        Cedex 07 — <a href="https://www.cnil.fr">cnil.fr</a>. If you live outside France, you may
        contact your own country's data protection authority instead.
      </p>

      <h2>10. Minors</h2>
      <p>
        The Service is for people aged 15 and older (the digital age of consent in France under
        GDPR Art. 8 as locally implemented). Creating an account requires declaring a date of
        birth, which the Service checks against this threshold; it does not independently verify
        age or identity. We do not knowingly collect data from anyone under 15. If you believe an
        account belongs to someone under 15, report it to contact@mytuums.com and it will be
        removed.
      </p>

      <h2>11. Discontinuation of the Service</h2>
      <p>
        The Service is a non-profit project run by one person. If it's permanently shut down,
        we'll try to give reasonable advance notice via the Service or by email, and give you a
        chance to export or request deletion of your data before it closes.
      </p>

      <h2>12. Changes to this policy</h2>
      <p>
        This policy may be updated, particularly as the Service or the law evolves. Material
        changes will be flagged via a notice on the Service or by email before they take effect.
        The "last updated" date at the top of this document reflects the version currently in
        force.
      </p>

      <h2>13. Contact</h2>
      <p>For any question about this policy or your data: contact@mytuums.com.</p>
    </>
  );
}
