/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=BrandingEnv worker/worker-configuration.d.ts` (hash: 3d4588c5bb9c44d3c86e6c541d2e70f4)
interface __BaseEnv_BrandingEnv {
  ASSETS: Fetcher;
  BRANDING_ORIGIN: "https://about-cf-poc.mytuums.com";
  ACCESS_TEAM_DOMAIN: "https://mytuums.cloudflareaccess.com";
  ACCESS_AUDIENCE: "7e8b9194813d7f984e385e9be12fbc34dbfd9b2244689c9b7fd19305fbb6026e";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_BrandingEnv {}
}
interface BrandingEnv extends __BaseEnv_BrandingEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "BRANDING_ORIGIN" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUDIENCE">
  > {}
}
