/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=BrandingEnv worker/worker-configuration.d.ts` (hash: 53f973e8971e45873fe2721033b82b2a)
interface __BaseEnv_BrandingEnv {
  ASSETS: Fetcher;
  BRANDING_ORIGIN: string;
  ACCESS_TEAM_DOMAIN: string;
  ACCESS_AUDIENCE: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_BrandingEnv {}
}
interface BrandingEnv extends __BaseEnv_BrandingEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "BRANDING_ORIGIN" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUDIENCE">
  > {}
}
