import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";

const sourceUrl = "https://www.unicode.org/Public/17.0.0/ucd/CaseFolding.txt";
const sourceHash = "ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183";
const localPath = process.argv[2];
const response = localPath ? undefined : await fetch(sourceUrl);
if (response && !response.ok) throw new Error(`Unicode download failed: ${response.status}`);
const source = localPath ? await readFile(localPath) : Buffer.from(await response!.arrayBuffer());
if (createHash("sha256").update(source).digest("hex") !== sourceHash)
  throw new Error("Unicode data checksum mismatch; review any version change explicitly.");

const groups = new Map<number, Set<number>>();
for (const line of source.toString("utf8").split("\n")) {
  const [code, status, mapping] = line.split(";").map((part) => part.trim());
  if (status !== "C" && status !== "S") continue;
  if (!/^[0-9A-F]+$/.test(code) || !/^[0-9A-F]+$/.test(mapping))
    throw new Error("Simple case folding must map one code point to one code point.");
  const from = Number.parseInt(code, 16);
  const to = Number.parseInt(mapping, 16);
  const group = groups.get(to) ?? new Set([to]);
  group.add(from);
  groups.set(to, group);
}
const equivalents = [...groups.entries()]
  .sort(([a], [b]) => a - b)
  .map(([, group]) =>
    [...group]
      .sort((a, b) => a - b)
      .map((point) => String.fromCodePoint(point))
      .join(""),
  );
const seen = new Set<string>();
for (const group of equivalents) {
  for (const character of group) {
    if (seen.has(character)) throw new Error("Case groups must be disjoint.");
    seen.add(character);
  }
}
await writeFile(
  new URL("../src/unicode-case-folding.generated.ts", import.meta.url),
  `// Generated by pnpm --filter @my-tuums/api generate:case-folding; do not edit.\n` +
    `// Unicode 17.0.0 simple case folding (C + S), from ${sourceUrl}\n` +
    `// SHA-256: ${sourceHash}\n` +
    `// Copyright © 2025 Unicode, Inc. See unicode-case-folding.LICENSE.txt.\n` +
    `export const SIMPLE_CASE_GROUPS: readonly string[] = ${JSON.stringify(equivalents)};\n`,
);
console.log(`Generated ${equivalents.length} Unicode simple-case groups.`);
