/** Regenerate only a NEW custom migration; never rewrite an applied migration. */
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { getConstructionPlans } from "pg-boss";
import { VIDEO_QUEUE_SCHEMA } from "../src/video-queue.js";

const filename = process.argv[2];
if (!filename || !/^\d{4}_[a-z0-9_]+\.sql$/.test(filename)) {
  throw new Error("Pass the filename created by drizzle-kit generate --custom.");
}
const plan = getConstructionPlans(VIDEO_QUEUE_SCHEMA).trim();
if (!plan.startsWith("BEGIN;") || !plan.endsWith("COMMIT;")) {
  throw new Error("The pg-boss construction plan's transaction format has changed.");
}
// Drizzle owns the transaction. Keep the vendor's procedural SQL intact;
// splitting on semicolons would break function bodies.
const body = plan.slice("BEGIN;".length, -"COMMIT;".length).trim();
await writeFile(
  resolve(import.meta.dirname, "../../db/drizzle", filename),
  `-- Generated by packages/api/scripts/generate-video-queue.ts from pinned pg-boss 12.26.0.\n${body}\n`,
);
