import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { SIMPLE_CASE_GROUPS } from "../src/unicode-case-folding.generated.js";

const sourceUrl =
  "https://raw.githubusercontent.com/postgres/postgres/REL_18_0/contrib/unaccent/unaccent.rules";
const sourceHash = "ecf4c41c0883dee17d02431e0a7f24a2611aadf8fe1da06e98c6ccb4acc4a981";
const localPath = process.argv[2];
const response = localPath ? undefined : await fetch(sourceUrl);
if (response && !response.ok) throw new Error(`Dictionary download failed: ${response.status}`);
const source = localPath ? await readFile(localPath) : Buffer.from(await response!.arrayBuffer());
if (createHash("sha256").update(source).digest("hex") !== sourceHash)
  throw new Error("Search dictionary checksum mismatch; review changes explicitly.");

const accents = new Map<string, string>();
for (const line of source.toString("utf8").trimEnd().split("\n")) {
  const match = /^(\S+)(?:\s+(.*))?$/u.exec(line);
  if (!match || Array.from(match[1]).length !== 1) throw new Error("Unsupported dictionary key.");
  const replacement = match[2] ?? "";
  accents.set(
    match[1],
    replacement.startsWith('"') ? replacement.slice(1, -1).replaceAll('""', '"') : replacement,
  );
}
const cases = new Map<string, string>();
for (const group of SIMPLE_CASE_GROUPS) {
  const characters = Array.from(group);
  const canonical = characters[0].replace(/[A-Z]/g, (letter) => letter.toLowerCase());
  for (const character of characters) cases.set(character, canonical);
}
const foldCase = (value: string) =>
  Array.from(
    value,
    (character) =>
      cases.get(character) ?? character.replace(/[A-Z]/g, (letter) => letter.toLowerCase()),
  ).join("");
const dictionary: Record<string, string> = {};
for (const character of new Set([...accents.keys(), ...cases.keys()])) {
  const folded = foldCase(accents.get(character) ?? character);
  // SQLite lower() already handles ASCII. Remaining keys are safe single-character JSON paths.
  if (character.codePointAt(0)! > 127 && folded !== character) dictionary[character] = folded;
}
await writeFile(
  new URL("../src/search-folding.generated.ts", import.meta.url),
  `// Generated by pnpm --filter @my-tuums/api generate:search-folding; do not edit.\n` +
    `// PostgreSQL 18.0 unaccent dictionary: ${sourceUrl}\n// SHA-256: ${sourceHash}\n` +
    `// See search-folding.LICENSE.txt and unicode-case-folding.LICENSE.txt.\n` +
    `export const SEARCH_FOLDING = new Map<string, string>(${JSON.stringify(Object.entries(dictionary))});\n`,
);
console.log(`Generated ${Object.keys(dictionary).length} search folding entries.`);
