/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=AppEnv worker/worker-configuration.d.ts` (hash: 130c0f1c2880174fa982494da3f3e7ed)
interface __BaseEnv_AppEnv {
  MEDIA: R2Bucket;
  DB: D1Database;
  EMAIL: SendEmail;
  IMAGES: ImagesBinding;
  STREAM: StreamBinding;
  ASSETS: Fetcher;
  WEB_ORIGIN: "https://preview.mytuums.com";
  ACCESS_TEAM_DOMAIN: "https://mytuums.cloudflareaccess.com";
  ACCESS_AUDIENCE: "6a8abc536bcca8df6a610bf39889bf089c297137124b0ce515dfb949130beca5";
  CLOUDFLARE_ACCOUNT_ID: "734f3b84571b1967e6940140a0b7d75f";
  STREAM_NAMESPACE: "mytuums-preview";
  EMAIL_FROM: "noreply@mytuums.com";
  BETTER_AUTH_SECRET: string;
  APPEAL_TOKEN_SECRET: string;
  STREAM_API_TOKEN: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  DISCORD_CLIENT_ID: string;
  DISCORD_CLIENT_SECRET: string;
  TWITCH_CLIENT_ID: string;
  TWITCH_CLIENT_SECRET: string;
  API_COUNTERS: DurableObjectNamespace<import("./index").RateLimitCounter>;
  AUTH_COUNTERS: DurableObjectNamespace<import("./index").AuthRateLimitCounter>;
  LINK_FETCHER: Service /* entrypoint LinkFetchService from mytuums-build-link-fetcher */;
  VIDEO_WORKFLOW: Workflow /* VideoWorkflow from mytuums-build-jobs */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
    durableNamespaces: "RateLimitCounter" | "AuthRateLimitCounter";
  }
  interface Env extends __BaseEnv_AppEnv {}
}
interface AppEnv extends __BaseEnv_AppEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "WEB_ORIGIN"
      | "ACCESS_TEAM_DOMAIN"
      | "ACCESS_AUDIENCE"
      | "CLOUDFLARE_ACCOUNT_ID"
      | "STREAM_NAMESPACE"
      | "EMAIL_FROM"
      | "BETTER_AUTH_SECRET"
      | "APPEAL_TOKEN_SECRET"
      | "STREAM_API_TOKEN"
      | "GOOGLE_CLIENT_ID"
      | "GOOGLE_CLIENT_SECRET"
      | "DISCORD_CLIENT_ID"
      | "DISCORD_CLIENT_SECRET"
      | "TWITCH_CLIENT_ID"
      | "TWITCH_CLIENT_SECRET"
    >
  > {}
}
