// Barrel joining the two schema halves: ./auth.ts is GENERATED by the
// better-auth CLI (`db:generate:auth`, never hand-edit) and ./app.ts is
// hand-written. drizzle.config.ts and packages/db/src/index.ts both point
// their `schema` at this file.
export * from "./auth.js";
export * from "./app.js";
