/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=LinkEnv worker/worker-configuration.d.ts` (hash: b8cf887ad306f887f568d6150cc42904)
interface __BaseEnv_LinkEnv {
  CONTAINER: DurableObjectNamespace<import("./index").LinkFetcherContainer>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
    durableNamespaces: "LinkFetcherContainer";
  }
  interface Env extends __BaseEnv_LinkEnv {}
}
interface LinkEnv extends __BaseEnv_LinkEnv {}
