// Keep the generated-file marker and refuse an accidental return to the
// PostgreSQL or second-resolution auth schema. The CLI's SQLite generator
// already emits timestamp_ms columns and millisecond SQL defaults.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const schemaPath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../src/schema/auth.ts",
);

const HEADER = `// GENERATED by @better-auth/cli, then post-processed — do not hand-edit.
// Regenerate with:
//   pnpm --filter @my-tuums/db db:generate:auth
// which runs the CLI and then ./scripts/patch-auth-schema.ts (that script's
// header explains what it changes and why). Application tables live in
// ./app.ts so regeneration never clobbers them.
`;

const original = readFileSync(schemaPath, "utf8");

// Drop whatever header is currently there, so re-running doesn't stack them.
const body = original.slice(original.indexOf("import "));

if (!body.includes('"drizzle-orm/sqlite-core"') || /mode:\s*"timestamp"/.test(body)) {
  throw new Error("Auth schema must use SQLite with millisecond timestamps");
}
const patched = HEADER + body;

if (patched === original) {
  console.log("auth.ts already patched; nothing to do.");
} else {
  writeFileSync(schemaPath, patched);
  console.log("Marked generated D1 auth schema.");
}
